In [128]:
import h5py
import numpy as np

In [ ]:
from IPython.display import HTML
from IPython.display import display
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation


def visualize_images(images, show=True, to_file = None):
    fig, ax = plt.subplots()
    x = ax.imshow(images[0])

    def update(frame):
        x.set_data(images[frame])
        return x

    ani = FuncAnimation(fig, update, frames=range(len(images)), interval=50)
    if to_file is not None:
        ani.save(to_file, writer='imagemagick', fps=30)
    if show:
        display(HTML(ani.to_html5_video()))
    plt.close()

In [129]:
file = h5py.File('../data/custom_rollouts_walk/CMU_016_15.hdf5', 'r')

In [139]:
clip = 'CMU_016_15-0-127'
print(file[f'{clip}/start_metrics'].keys())
start_lens = np.array(file[f'{clip}/start_metrics/episode_lengths'][()])
rsi_lens = np.array(file[f'{clip}/rsi_metrics/episode_lengths'][()])
print(f"start {start_lens.mean():6.2f} +- {start_lens.std():6.2f}, range {start_lens.min():3d} - {start_lens.max():3d}")
print(f"rsi   {rsi_lens.mean():6.2f} +- {rsi_lens.std():6.2f}, range {rsi_lens.min():3d} - {rsi_lens.max():3d}")

<KeysViewHDF5 ['episode_lengths', 'episode_returns', 'norm_episode_lengths', 'norm_episode_returns']>
start 408.09 +- 250.09, range  79 - 1679
rsi   427.63 +- 275.44, range  27 - 1907


In [140]:
# file = h5py.File('../data/custom_rollouts_debug1/CMU_016_15.hdf5', 'r')
# file = h5py.File('../data/custom_rollouts_run/CMU_016_55.hdf5', 'r')
# file = h5py.File('../data/custom_rollouts_walk_debug/CMU_016_15.hdf5', 'r')
file = h5py.File('../data/custom_rollouts_jogging_images_01/CMU_016_36.hdf5', 'r')

In [141]:
clip = 'CMU_016_55-0-47'
clip = 'CMU_016_15-0-127'
clip = 'CMU_016_36-0-49'
print(file[f'{clip}/early_termination'][()])
print(file[f'{clip}'].keys())
print(file[f'{clip}/start_metrics'].keys())
file[f'{clip}/start_metrics/episode_lengths'][()], file[f'{clip}/rsi_metrics/episode_lengths'][()]

[ True  True]
<KeysViewHDF5 ['0', '1', 'early_termination', 'rsi_metrics', 'start_metrics']>
<KeysViewHDF5 ['episode_lengths', 'episode_returns', 'norm_episode_lengths', 'norm_episode_returns']>


(array([479]), array([479]))

In [142]:
file[f'{clip}/0/images'].shape

(479, 480, 640, 3)

In [143]:
ims = file[f'{clip}/0/images']
visualize_images(ims)

In [4]:
file = h5py.File('../data/custom_rollouts/CMU_016_15.hdf5', 'r')
file.keys()

<KeysViewHDF5 ['CMU_016_15-0-127', 'n_rsi_rollouts', 'n_start_rollouts', 'observable_indices', 'ref_steps', 'stats']>

In [38]:
for key in file['CMU_016_15-0-127/0'].keys():
    try:
        print(key, file[f'CMU_016_15-0-127/0/{key}'].shape)
    except AttributeError:
        print(f'{key}/proprioceptive', file[f'CMU_016_15-0-127/0/{key}/proprioceptive'].shape)

actions (122, 56)
advantages (122,)
mean_actions (122, 56)
observations/proprioceptive (123, 2868)
rewards (122,)
values (122,)


In [42]:
file['CMU_016_15-0-127/rsi_metrics/episode_lengths'][()]

array([ 85,  91,  94, 100,  88,  99,  75,  71, 102,  81,  94,  92,  73,
       119, 118, 121,  78,  81,  76,  71])

In [43]:
file['CMU_016_15-0-127/start_metrics/episode_lengths'][()]

array([122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122,
       122, 122, 122, 122, 122, 122, 122])

In [44]:
file['CMU_016_15-0-127/early_termination'][()]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [20]:
file['n_rsi_rollouts'][()], file['n_start_rollouts'][()], file['ref_steps'][()]

(20, 20, array([1, 2, 3, 4, 5]))

In [23]:
file['stats'].keys()

<KeysViewHDF5 ['act_mean', 'act_var', 'count', 'mean_act_mean', 'mean_act_var', 'proprio_mean', 'proprio_var']>

In [18]:
print(file['observable_indices/walker/time_in_clip'][()])
print(file['observable_indices/walker/appendages_pos'][()])

[2856]
[56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
